GET http://localhost:8080/dirty-secrets/count

###

GET http://localhost:8080/dirty-secrets/test-123

###

POST http://127.0.0.1:8080/dirty-secrets
Content-Type: application/json

{
    "name": "Freddy",
    "secret": "Killed an elderly couple and did time."
}

{
    "name": "Doug",
    "secret": "Former Alcoholic."
}